from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text
from datetime import datetime
from app.core.database import Base


class Client(Base):
    __tablename__ = "clients"

    id = Column(Integer, primary_key=True, autoincrement=True)
    numero_client = Column(String, unique=True, nullable=False, index=True)
    nom = Column(String, nullable=False)
    prenoms = Column(String, nullable=False)
    date_naissance = Column(DateTime, nullable=True)
    lieu_naissance = Column(String, nullable=True)
    sexe = Column(String, nullable=True)
    numero_cni = Column(String, nullable=True)
    numero_passeport = Column(String, nullable=True)
    telephone = Column(String, nullable=True)
    email = Column(String, nullable=True)
    whatsapp = Column(String, nullable=True)
    adresse = Column(String, nullable=True)
    situation_familiale = Column(String, nullable=True)
    nombre_enfants = Column(Integer, nullable=True)
    type_logement = Column(String, nullable=True)
    description_logement = Column(Text, nullable=True)
    langues_parlees = Column(String, nullable=True)
    reference_nom_1 = Column(String, nullable=True)
    reference_tel_1 = Column(String, nullable=True)
    reference_relation_1 = Column(String, nullable=True)
    reference_nom_2 = Column(String, nullable=True)
    reference_tel_2 = Column(String, nullable=True)
    reference_relation_2 = Column(String, nullable=True)
    activite_principale = Column(String, nullable=True)
    activites_secondaires = Column(Text, nullable=True)
    revenus_mensuels = Column(Float, nullable=True)
    charges_mensuelles = Column(Float, nullable=True)
    capacite_remboursement = Column(Float, nullable=True)
    anciennete_activite = Column(Integer, nullable=True)
    lieu_exercice_activite = Column(String, nullable=True)
    description_activite = Column(Text, nullable=True)
    biens_patrimoine = Column(Text, nullable=True)
    groupe_solidaire_id = Column(Integer, nullable=True)
    caution_solidaire_active = Column(Boolean, default=False)
    score_credit = Column(Integer, default=50)
    niveau_risque = Column(String, default="Moyen")  # Faible, Moyen, Élevé
    capacite_endettement = Column(Float, nullable=True)
    taux_endettement = Column(Float, nullable=True)
    montant_max_autorise = Column(Float, nullable=True)
    date_creation = Column(DateTime, default=datetime.utcnow)
    agence = Column(String, nullable=True)
    agent_affecte = Column(String, nullable=True)
    photo_path = Column(String, nullable=True)
    document_cni_path = Column(String, nullable=True)
    document_justif_domicile_path = Column(String, nullable=True)
    photo_commerce_path = Column(String, nullable=True)
    photo_domicile_path = Column(String, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    statut = Column(String, default="Actif")  # Actif, Inactif, Blacklisté
    date_evaluation = Column(DateTime, nullable=True)
    epargne_obligatoire_ouverte = Column(Boolean, default=False)
